### ISSUE TITLE
v2019.1 tracking issue

### ISSUE THREAD

**Issue by mweinelt** [freifunk-gluon/gluon#1779]
All blockers seem to be gone so let's start the countdown to v2019.1.

- [x] release notes #1815
  - #1715 
- [x] traffic shaping is broken https://github.com/freifunk-gluon/gluon/issues/1790
- [x] batman-adv coexistence https://github.com/freifunk-gluon/gluon/pull/1622
- [x] fritzbox 4040 bootloader https://github.com/freifunk-gluon/gluon/issues/1766
- [x] ramips-rt305x builds https://github.com/freifunk-gluon/gluon/pull/1807
- [x] gluon-web-wifi-config https://github.com/freifunk-gluon/gluon/issues/1809

Anything else?

**Comment by rotanid** [comment]
one issue is definitely still marked as a blocker #1715 
and i find it kind of odd to not include something not because we're waiting on something but because someone is waiting for us #1622

**Comment by mweinelt** [comment]
#1715 is a docs issue that goes into the release notes

**Comment by bobcanthelpyou** [comment]
Maybe #1784 (as there is a fix for a msgid of gluon-web-wifi-config) but mostly it is just "reorganization of strings and lines".

**Comment by rotanid** [comment]
#1790 came up as a new blocker ~2 weeks ago
