### ISSUE TITLE
respondd structural roadmap

### ISSUE THREAD

**Issue by christf** [freifunk-gluon/gluon#1903]
We currently support multiple mesh/routing protocols that each have their respondd module. 
Each module implements statistics including nic traffic, information about neighbours and routing.
Some technologies are fundamentally different between mesh protocol implementations, however others are the same:

- [ ] iterating over mesh interfaces (use UCI)
- [ ] iterating over all interfaces (use UCI)
- [ ] obtaining NIC traffic statistics
- [ ] the gateway_nexthop field should be adusted to match https://github.com/FreifunkBremen/yanic/issues/170 un-batman-i-fying this part of the response structure.
- [ ] Large respondd.c implementations should be broken down into statistics, nodeinfo and neighbour files as done in #1879 for the batman module.

**Comment by genofire** [comment]
is there any update on this, or could we close the yanic issue?
