### ISSUE TITLE
ipq40xx - DSA migration process

### ISSUE THREAD

**Issue by AiyionPrime** [freifunk-gluon/gluon#2666]
Similar, yet incomparably simpler than #2413 this is tracking the DSA migration following https://github.com/openwrt/openwrt/pull/4721 and related patches.

The workflow would be: find your model, make sure it has DSA support in OpenWrt report back whether it is done or not, needs changes or has no support in OpenWrt and should therefore be dropped.

**missing DSA setup**

- ~~engenius-ens620ext~~ The device appears to be absent in each community, no need for migrations.
- ~~zyxel-wre6606~~ The device appears to be absent in each community, no need for migrations.

**done**

- [x] 8devices-jalapeno
- [x] aruba-ap-303 (aruba-instant-on-ap11)
- [x] aruba-ap-303h (aruba-instant-on-ap11d)
- [x] aruba-ap-365 (aruba_ap-365)
- [x] avm-fritz-box-4040
- [x] avm-fritz-box-7530
- [x] avm-fritz-repeater-1200
- [x] gl.inet-gl-ap1300
- [x] gl.inet-gl-b1300
- [x] linksys-ea6350v3
- [x] mikrotik-sxtsq-5-ac-rbsxtsqg-5acd (mikrotik-discg-5acd)
- [x] netgear-ex6100v2
- [x] netgear-ex6150v2
- [x] openmesh-a42
- [x] openmesh-a62
- [x] plasma-cloud-pa1200
- [x] plasma-cloud-pa2200
- [x] zyxel-nbg6617

**Comment by blocktrron** [comment]
@AiyionPrime I think the AP-303 as well as 4040 are already migrated? A full re-validation is not necessary downstream, as it is performed upstream. We also didn't do it for neither mt7621 nor xrx200

**Comment by ecsv** [comment]
* Pending Open-Mesh: https://github.com/openwrt/openwrt/pull/11078
* Pending PlasmaCloud: https://github.com/openwrt/openwrt/pull/11083

**Comment by AiyionPrime** [comment]
I've got a notifier to monitor these changes in that part of openwrt's tree; once they make it to master, I'll mark them as done.

**Comment by AiyionPrime** [comment]
updated the tracker, thanks @ecsv!

**Comment by AiyionPrime** [comment]
Pending GL.iNet: https://github.com/openwrt/openwrt/pull/10909

**Comment by rotanid** [comment]
i do own some netgear-ex6150v2, but i'm not sure i can help. maybe @mbaumga ?

**Comment by AiyionPrime** [comment]
* Pending Aruba: https://github.com/openwrt/openwrt/pull/11579

**Comment by JJWatMyself** [comment]
Aruba ap-303h tests are good and have reported this on the other thread a few minutes ago. There are two items I have identified to address in the future, but not specific to DSA.

I also flagged an invisible font/font color issue on the default theme, but will likely need to log a bug somewhere.

**Comment by JJWatMyself** [comment]
Ok, DSA for Aruba AP-303H is live in the snapshot and I have verified.  I am running dumb AP with many VLANs and wired ports configured to do VLANs also.

https://github.com/openwrt/openwrt/pull/11579#issuecomment-1367888343

![image](https://user-images.githubusercontent.com/22590445/210069289-4c19cd79-10a2-4035-86e8-be9c4e8ac53a.png)

**Comment by Djfe** [comment]
I'm going to fix this upstream for the `zyxel-wre6606`
Maybe also for the `netgear-ex6150v2`

**Comment by AiyionPrime** [comment]
Hey there. Any chance you still have access to the device you added support for in OpenWrt? It currently doesn't get built, maybe you can help addressing the issue in an efficient manner.

- https://github.com/openwrt/openwrt/commit/300b7fe85a743ab0e039457a5a551819b49450da @blocktrron Aruba AP-365
- https://github.com/openwrt/openwrt/commit/dc4f6b896f009c24170e75af745fc636ef8166a8 @steveglennon EnGenius ENS620EXT
- https://github.com/openwrt/openwrt/commit/970f1914be3f299fb302ca74a214589397000858 @blocktrron Netgear EX6100v2/EX6150v2
- https://github.com/openwrt/openwrt/commit/4b280ad91a6b155ac71c417aaa7bb5f4e328712f @skorpy2009 ZyXEL WRE6606

**Comment by Djfe** [comment]
I kinda stopped after the Zyxel didn't want to boot anymore and I wasn't able to interrupt boot anymore since then.
I'll try to get around to it this weekend but start with the EX6150v2 since it's easy to recover.

**Comment by steveglennon** [comment]
I still have access. I will look into it.
Steve

Sent from my iPhone

On Feb 24, 2023, at 8:03 AM, Felix Baumann ***@***.***> wrote:

﻿

I kinda stopped after the Zyxel didn't want to boot anymore and I wasn't able to interrupt boot anymore since then.
I'll try to get around to it this weekend but start with the EX6150v2 since it's easy to recover.

**Comment by AiyionPrime** [comment]
@blocktrron committed https://github.com/openwrt/openwrt/commit/bf055fcdca155993b9b6c82f951000eefb13288a

So 6100v2 and 6150v2 are done.

**Comment by skorpy2009** [comment]
@AiyionPrime @blocktrron 
What do I have to do:

```
https://github.com/openwrt/openwrt/commit/4b280ad91a6b155ac71c417aaa7bb5f4e328712f @skorpy2009 ZyXEL WRE6606

    https://github.com/openwrt/openwrt/blob/master/target/linux/ipq40xx/image/generic.mk#L1194-L1195
```

**Comment by Djfe** [comment]
test this https://github.com/Djfe/openwrt/commit/9c2353c61b9b9f2a7aa12c873a5f44b16f2b9fbb
I need to recover my device still, else I would have already done a PR.
One of the swports (switch ports) will come up as an interface, that's the one we need to keep then.

**Comment by Djfe** [comment]
Update on my part:
I finally figured out what broke my Zyxel wre6606
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=45eb57f12f3a128a1822a20b7e536527ab92ca67
The kernel got too large and the bootloader doesn't load it fully.
I might've to increase the compat version so people don't accidentally brick their device by upgrading without adjusting bootcmd first.

Apart from that I still have that pesty issue that the wre6606 isn't reacting to any of my keyboard inputs.
While connecting tx to rx on my ttl directly with a cable works just fine.
I tested with screen, picocom and gtkterm.

Other devices I used my ttl adapter with so far didn't receive my tx either.
Next test: using an openwrt Router with ssh as my ttl Adapter.

**Comment by mkg20001** [comment]
I tested hap ac2 (ipq40xx-mikrotik) as it gained dsa aswell. It has an increased compat version so I had to manually increment it in uci system compat_version to install the upgrade. Everything came up after upgrading. No new problems yet.

**Comment by Djfe** [comment]
did you test openwrt or gluon?

**Comment by mkg20001** [comment]
gluon, but installed image via sysupgrade and built from next branch.

**Comment by AiyionPrime** [comment]
@Djfe I haven't heard of your last test in a while now;
would you mind if we just mark the remaining two devices as out of reach and complete this issue?

> Update on my part: I finally figured out what broke my Zyxel wre6606 https://git.openwrt.org/?p=openwrt/openwrt.git;a=commit;h=45eb57f12f3a128a1822a20b7e536527ab92ca67 The kernel got too large and the bootloader doesn't load it fully. I might've to increase the compat version so people don't accidentally brick their device by upgrading without adjusting bootcmd first.
> 
> Apart from that I still have that pesty issue that the wre6606 isn't reacting to any of my keyboard inputs. While connecting tx to rx on my ttl directly with a cable works just fine. I tested with screen, picocom and gtkterm.
> 
> Other devices I used my ttl adapter with so far didn't receive my tx either. Next test: using an openwrt Router with ssh as my ttl Adapter.

**Comment by Djfe** [comment]
Feel free to close this issue. I might work on it again at some point just to get the device into OpenWrt again but I already worked on it in 2023 and eventually got demotivated because I couldn't get it to work.

for completeness, the last update on that part (from September 2023):
https://github.com/Djfe/openwrt/commit/5cd4e0c1d8bb101a21e491a84d99183c22a13273
while the kernel got too large, I was able to solve this with the help of others (without increasing compat version) simply by switching to a FitzImage.
I was able to get it to boot and wifi also works. But I could not get the ethernet to work using DSA. I wrote back and forth with robimarko a few times and sent him output of ethtool. But eventually the project just sat there/I stopped working on it. He was also confused because every other ipq40xx device worked fine using DSA and my dts and everything looked correct/fine.

The issues with serial which really demotivated me back then were due to a fake serial/ttl chip. rx worked while tx didn't.

**Comment by AiyionPrime** [comment]
Thanks for everyone involved, we are done migrating all models, which currently have devices in the field.
