### ISSUE TITLE
check existing PRs for linting issues 

### ISSUE THREAD

**Issue by AiyionPrime** [freifunk-gluon/gluon#2765]
Existing PRs have mostly not been checked against the new editorconfig linting added in #2758.

In order to test this, one could rebase the PR onto master and push the branch,
or at least verify its integrity locally with `make lint-editorconfig` to reduce unnecessary stress on our infrastructure.

affected PRs:

None - Nothing left to do here.
The remaining PRs should meet the editorconfig-checker on their own eventually.

tested:

- [x] #2654 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2366 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2367 @AiyionPrime [(locally ran `make lint-editorconfig`)](https://github.com/freifunk-gluon/gluon/pull/2367#issuecomment-1399270560)
- [x] #2516 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2535 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2739 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2737 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2580 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2595 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2597 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2614 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2684 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2688 @AiyionPrime [(locally ran `make lint-editorconfig`)](https://github.com/freifunk-gluon/gluon/pull/2688#issuecomment-1399274954)
- [x] #2695 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2714 @AiyionPrime (locally ran `make lint-editorconfig`)
- [x] #2720 @AiyionPrime (locally ran `make lint-editorconfig`)

merge conflict (need to be rebased anyway, the action will run then):

- [x] ~#1568~ 
- [x] ~#1799~
- [x] ~#1808~
- [x] ~#2246~
- [x] ~#2418~
- [x] ~#2465~
- [x] ~#2552~
- [x] ~#2601~

linting is already failing due to other reasons (need to be rebased anyway, the action will run then):

- [x] ~#2296~
