### ISSUE TITLE
Pending device backports

### ISSUE THREAD

**Issue by AiyionPrime** [freifunk-gluon/gluon#2855]
We talked about device backports on the last meetup, which we neglected a little in the past.
Someone argued we should retain the order of commits if possible.

**edit** these are the PRs which added or modified target/* in commit order:

- ~~#2637~~
  - [x] already backported in #2649
- ~~#2633~~
  - [x] already backported in #2649
- ~~#2635~~
  - [x] already backported in #2649
- ~~#2640~~
  - [x] already backported in #2641
- #2659
  - apparently not worth backporting
- ~~#2664~~
  - [x] already backported in #2667
- ~~#2671~~
  - [x] already backported in #2675
- ~~#2673~~
  - [x] already backported in #2677
- #2681
  - [x] already backported in in #2863
- ~~#2689~~ **broken**
- #2554
  - [x] already backported in #2869
- #2700 
  - [x] already backported in #2871
- #2712 
  - [x] already backported in #2872
- #2707
  - [x] already backported in #2873
- #2738
  - [x] already backported in #2875
- #2706
  - [x] already backported in #2874
- ~~#2710~~ **would need @blocktrron's LTE code**
- ~~#2716~~ **broken**
- #2595
  - [x] already backported in #2876
- ~~#2768~~ **would need @blocktrron's LTE code**
- #2654
  - [x] pending backport
- ~~#2813~~
  - [x] already backported in #2851
- ~~#2817~~
  - [x] already backported in #2819
- ~~#2831~~
  - [x] already backported in #2851
- ~~#2842~~
  - [x] already backported in #2843
- ~~#2830~~
  - [x] already backported in #2851
- (#2848) _might be useful to backport as well_

**Comment by rotanid** [comment]
> I'll create a list of device PRs which could be backported, if we found a tester for them.

why would we need to re-test if the stable branch (currently v2022.1.x) is using the same openwrt branch for which the device support was already tested in master branch?

**Comment by AiyionPrime** [comment]
I wrote it down, because we talked about it in the last meetup.
The idea was that the devices we are going to backport have been in master for a while now and may have received additional fixes we might miss else.

I have no strong opinion on this.

**Comment by maurerle** [comment]
Then I will add those two to the list here, so that they can be merged in the right order:
#2681
 
#2863

**Comment by AiyionPrime** [comment]
#2861 is 'only' adding an openwrt patch and not changing target files.
It does not need to follow this order.

The other one is reflected in the list above. I'd mark your comment as resolved, to keep this as clean as possible.

**Comment by AiyionPrime** [comment]
That was it.
